version: "3.7"

services:
  mc:
    restart: unless-stopped
    container_name: minecraft
    image: itzg/minecraft-server:java8
    volumes:
      - ./files:/data
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      DEBUG: "false"
      VERSION: "1.16.5"
      FORGEVERSION: "36.2.39"
      MEMORY: "16G"
      OPS: "BideoGemu"
      LEVEL_TYPE: skyblockbuilder\:custom_skyblock
      ALLOW_FLIGHT: "true"
      MOTD: "BlackStone Block On Docker"
    tty: true
    stdin_open: true

volumes:
  files: {}
